// remotion_input.json schema (generated by tools/remotion/prepare_remotion.py).
// Timeline uses measured durations from production/audio/durations.json;
// segments without synthesized audio fall back to "estimated".

export interface SentenceTiming {
  text: string;
  start: number;
  end: number;
}

export interface SegmentInput {
  order: number;
  id: string;
  /** slide id in visual.html, e.g. "s2"; null for the END slot */
  slide: string | null;
  /** slide PNG under public/; null -> render end card in code */
  image: string | null;
  /** audio under public/ (TTS WAV, opening/ending BGM); null -> silent */
  audio: string | null;
  durationSec: number;
  timingSource: "measured" | "estimated";
  title: string;
  corner: string;
  /** corner-change head: play transition sting on top */
  sting: boolean;
  sentences: SentenceTiming[];
  /** ending slot only: greeting speech end (sec); EndCard fades in after it */
  speechEndSec?: number;
  /** fixed ending slot: disclaimer hold ends and EndCard replaces this slide */
  endCardAtSec?: number;
  /** exact visual state for crossfade grouping; falls back to segment id */
  stateKey?: string;
}

export interface EpisodeInput {
  episode: string;
  dateJa: string;
  fps: number;
  width: number;
  height: number;
  bgmBed: string | null;
  /** transition sting file under public/ (null -> no sting) */
  stingFile: string | null;
  /** sting length in frames (default 150 = 5s at 30fps) */
  stingFrames?: number;
  segments: SegmentInput[];
}
