"""Final quality gate: mechanical checks + optional LLM semantic review.

Mechanical (code, zero tokens):
  1. Japanese vocab / simplified char scan (check_japanese.py)
  2. Draft length validation (check_draft_length.py)
  3. Episode contract validation (build_pipeline.py validate)
  4. Artifact chain completeness (build_pipeline.py check-artifacts)

Semantic (1 pro API call, optional):
  5. Compliance + actionability + depth review

Usage:
  python final_qa.py 2026-09-12
  python final_qa.py 2026-09-12 --skip-semantic     # mechanical only
  python final_qa.py 2026-09-12 --semantic-only     # semantic review only
  python final_qa.py 2026-09-12 --post-render       # artifacts only, no content review
"""
from __future__ import annotations

import argparse
import io
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = sys.stdout.__class__(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = sys.stderr.__class__(sys.stderr.buffer, encoding="utf-8", errors="replace")

_TOOLS_DIR = Path(__file__).resolve().parent
_US_ROOT = _TOOLS_DIR.parents[1]
sys.path.insert(0, str(_TOOLS_DIR))

import text_llm  # noqa: E402


def _run_check(args: list[str], label: str) -> tuple[bool, str]:
    """Run a subprocess check. Returns (passed, output)."""
    try:
        result = subprocess.run(
            args, capture_output=True, text=True, timeout=300,
            cwd=str(_US_ROOT), encoding="utf-8", errors="replace",
        )
        output = (result.stdout or "") + (result.stderr or "")
        return result.returncode == 0, output
    except subprocess.TimeoutExpired:
        return False, f"{label}: timed out after 300s"
    except FileNotFoundError as e:
        return False, f"{label}: command not found: {e}"


def run_mechanical(date: str, *, pre_tts: bool = False) -> list[dict]:
    """Run all code-based checks. Returns list of check results."""
    checks: list[dict] = []

    def _add(name: str, passed: bool, output: str) -> None:
        checks.append({"check": name, "passed": passed, "output": output[-2000:]})
        icon = "PASS" if passed else "FAIL"
        print(f"  [{icon}] {name}")
        if not passed:
            for line in output.strip().splitlines()[-5:]:
                print(f"         {line}")

    py = sys.executable

    passed, out = _run_check([py, str(_US_ROOT / "tools" / "check_japanese.py"), date], "japanese")
    _add("japanese_vocab_and_simplified", passed, out)

    passed, out = _run_check([py, str(_US_ROOT / "tools" / "check_draft_length.py"), date], "length")
    _add("draft_length", passed, out)

    passed, out = _run_check(
        [py, str(_TOOLS_DIR.parent / "orchestrator" / "build_pipeline.py"), "validate", "--date", date],
        "contract",
    )
    _add("episode_contract", passed, out)

    passed, out = _run_check(
        [py, str(_TOOLS_DIR.parent / "orchestrator" / "build_pipeline.py"), "check-artifacts", "--date", date],
        "artifacts",
    )
    missing = [line for line in out.splitlines() if "missing file" in line]
    audio_only = bool(missing) and all(
        line.rstrip().endswith("durations.json") for line in missing
    )
    if pre_tts and audio_only:
        passed = True
        out += ("\n[pre-tts] audio durations are generated by the tts stage; "
                "full artifact chain is checked after TTS.")
    _add("artifact_chain", passed, out)

    # Visual references are not just a render concern: a stale path can become
    # a blank frame even when the HTML file itself exists.
    visual_data = _US_ROOT / "daily-output" / date / "production" / "visual-data.json"
    if visual_data.is_file():
        issue = _US_ROOT / "daily-output" / date
        data = json.loads(visual_data.read_text(encoding="utf-8-sig"))
        missing_imgs = []
        for slide_id, html in sorted(data.get("slices", {}).items()):
            for src in __import__("re").findall(
                    r"<img[^>]+src=[\"']([^\"']+)[\"']", html, __import__("re").I):
                if "logo.png" in src or src.startswith("data:"):
                    continue
                p = issue / src
                if not p.is_file() or p.stat().st_size < 10_000:
                    missing_imgs.append(f"{slide_id}: {src}")
        passed = not missing_imgs
        out = "all referenced visual assets exist" if passed else "\n".join(missing_imgs)
        _add("visual_asset_refs", passed, out)

    # Portrait metadata must exist for every B page image and stay in sync
    # with the slice HTML class (portrait circle vs full-height photo).
    issue = _US_ROOT / "daily-output" / date
    meta_path = issue / "assets" / "image-meta.json"
    brief_path = issue / "production" / "visual-brief.md"
    if meta_path.is_file() and visual_data.is_file():
        import re as _re
        meta = json.loads(meta_path.read_text(encoding="utf-8-sig"))
        data = json.loads(visual_data.read_text(encoding="utf-8-sig"))
        all_html = "\n".join(data.get("slices", {}).values())
        errors: list[str] = []
        if brief_path.is_file():
            for line in brief_path.read_text(encoding="utf-8-sig").splitlines():
                if not line.startswith("| s"):
                    continue
                cols = [c.strip() for c in line.strip("|").split("|")]
                if len(cols) >= 7 and _re.fullmatch(r"B\d+-p\d+", cols[1]):
                    if cols[1] not in meta:
                        errors.append(f"{cols[1]}: no image-meta entry")
        for block, info in sorted(meta.items()):
            asset = info.get("asset", "")
            if not (issue / asset).is_file() or (issue / asset).stat().st_size < 10_000:
                errors.append(f"{block}: meta asset missing: {asset}")
            if not info.get("keyword"):
                errors.append(f"{block}: keyword not recorded")
            if not isinstance(info.get("portrait"), bool):
                errors.append(f"{block}: portrait flag not boolean")
            plain = f'<div class="photo-frame"><img src="{asset}"'
            circle = f'<div class="photo-frame portrait"><img src="{asset}"'
            if info.get("portrait") and plain in all_html and circle not in all_html:
                errors.append(f"{block}: portrait image rendered without circle class")
            if not info.get("portrait") and circle in all_html:
                errors.append(f"{block}: non-portrait image rendered as circle")
        passed = not errors
        out = "image metadata and portrait styles consistent" if passed else "\n".join(errors)
        _add("visual_image_meta", passed, out)

    # Preview-v2 (2026-09-19+): s1 is the single preview list page. It must
    # show only titles, cycle every theme's p1 photo, and omit summaries.
    if str(date) >= "2026-09-19" and visual_data.is_file():
        import re as _re
        data = json.loads(visual_data.read_text(encoding="utf-8-sig"))
        brief_path = issue / "production" / "visual-brief.json"
        preview = {}
        if brief_path.is_file():
            brief = json.loads(brief_path.read_text(encoding="utf-8-sig"))
            preview = brief.get("preview", {})
            themes = brief.get("themes", [])
        count = len(preview.get("items", []))
        html = data.get("slices", {}).get("s1", "")
        errors: list[str] = []
        if count and not html:
            errors.append("s1: preview list page missing")
        else:
            title_items = _re.findall(
                r'<div class="topic-item[^"]*"><div class="topic-number">\d+</div>'
                r'<div class="topic-title">([^<]*)</div></div>',
                html,
            )
            if count and len(title_items) != count:
                errors.append(
                    f"s1: expected {count} title items, found {len(title_items)}"
                )
            if count and [_re.sub(r"\s+", "", item) for item in title_items] != [
                _re.sub(r"\s+", "", str(preview_item.get("title", "")))
                for preview_item in preview.get("items", [])
            ]:
                errors.append(
                    "s1: preview title order/content does not match visual-brief.json"
                )
            summaries = [t.get("summary", "") for t in themes]
            for summary in summaries:
                clean = _re.sub(r"\[pause[^\]]*\]", "", summary)
                clean = _re.sub(r"\s+", "", clean)
                if clean and clean[:10] in _re.sub(r"\s+", "", html):
                    errors.append(
                        "s1: summary text must not be rendered on screen"
                    )
                    break
            for i in range(1, count + 1):
                if f"assets/b{i}-1.png" not in html:
                    errors.append(f"s1: missing theme photo assets/b{i}-1.png")
        passed = not errors
        out = "s1 preview list shows titles only with every theme photo" \
            if passed else "\n".join(errors)
        _add("preview_list_s1", passed, out)

    return checks


def run_semantic_review(date: str) -> dict:
    """Run one LLM semantic review pass. Returns structured result."""
    issue = _US_ROOT / "daily-output" / date
    script_path = issue / "production" / "script.json"
    if not script_path.is_file():
        return {"passed": False, "errors": ["script.json not found"]}

    script = json.loads(script_path.read_text(encoding="utf-8-sig"))
    full_text = "\n\n".join(
        f"== {b.get('id', '?')} ==\n{b.get('text', '')}"
        for b in script.get("blocks", []) if isinstance(b, dict)
    )
    # Truncate to fit context budget.
    if len(full_text) > 40000:
        full_text = full_text[:40000] + "\n... (truncated)"

    prompt = f"""あなたは日本の証券・資産運用業界のコンプライアンス担当であり、
投資番組の最終品質チェックを担当しています。以下の放送台本を審査し、
問題があれば JSON で報告してください。

【チェック項目】
1. コンプライアンス: 直接的な売買推奨がないか（「私ならこう動きます」形式は OK）
2. コンプライアンス: 収益率の保証がないか
3. コンプライアンス: ナレーション本文に免責事項が含まれていないか
   （免責は番組末尾のEND静止画でのみ表示する。台本テキストに
   「投資判断を助ける情報提供」等の免責文があればエラーとする）
4. アクション指針（鉄則二）: 個別株/セクターに大手目標株価＋アクション価格があるか
5. 情報源: 主要な数字に出所が明記されているか
6. 深度: 表面的なニュース羅列でなく、因果・構造・リスクの分析があるか
7. 日本語: 不自然な直訳や簡体字の残りがないか

【放送台本】
{full_text}

【出力形式】有効な JSON のみ:
{{
  "passed": true/false,
  "errors": ["具体的な問題の説明（block ID と行内容を引用）"],
  "warnings": ["警告レベルの指摘"],
  "compliance_ok": true/false,
  "actionability_ok": true/false,
  "depth_ok": true/false
}}"""

    schema = json.dumps({
        "type": "object",
        "required": ["passed", "errors"],
        "properties": {
            "passed": {"type": "boolean"},
            "errors": {"type": "array", "items": {"type": "string"}},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
    })
    try:
        result = text_llm.generate_json(prompt, tier="pro", schema_hint=schema)
    except Exception as e:
        print(f"  [WARN] semantic review API call failed: {e}")
        return {"passed": None, "errors": [], "api_error": str(e)}

    icon = "PASS" if result.get("passed") else "FAIL" if result.get("passed") is False else "SKIP"
    print(f"  [{icon}] semantic_review")
    for e in result.get("errors", [])[:5]:
        print(f"         ERROR: {e}")
    for w in result.get("warnings", [])[:3]:
        print(f"         WARN: {w}")
    return result


def run_post_render(date: str) -> list[dict]:
    """Verify synthesized/rendered artifacts only. Content was QA'd pre-TTS."""
    issue = _US_ROOT / "daily-output" / date
    checks: list[dict] = []

    def _add(name: str, passed: bool, output: str) -> None:
        checks.append({"check": name, "passed": passed, "output": output[-2000:]})
        icon = "PASS" if passed else "FAIL"
        print(f"  [{icon}] {name}")
        if not passed:
            for line in output.strip().splitlines()[-5:]:
                print(f"         {line}")

    durations_path = issue / "production" / "audio" / "durations.json"
    if not durations_path.is_file():
        _add("audio_durations", False, "durations.json not found")
    else:
        durations = json.loads(durations_path.read_text(encoding="utf-8-sig"))
        rows = durations.get("segments", [])
        missing = []
        for row in rows:
            rel = row.get("file", "")
            if not rel or not (issue / rel).is_file():
                missing.append(row.get("id", "?"))
        _add(
            "audio_durations",
            not missing,
            f"{len(rows)} merged segment(s) present"
            if not missing else "missing merged audio: " + ", ".join(missing),
        )

    episode_path = issue / "episode.mp4"
    if episode_path.is_file() and episode_path.stat().st_size > 1_000_000:
        _add("episode_video", True, f"episode.mp4 ({episode_path.stat().st_size} bytes)")
    else:
        _add("episode_video", False, "episode.mp4 missing or too small")

    return checks


def main() -> int:
    parser = argparse.ArgumentParser(description="Final quality gate")
    parser.add_argument("issue_date", help="episode date (YYYY-MM-DD)")
    parser.add_argument("--skip-semantic", action="store_true")
    parser.add_argument("--semantic-only", action="store_true")
    parser.add_argument("--pre-tts", action="store_true",
                        help="defer audio artifact completeness to post-tts QA")
    parser.add_argument("--post-render", action="store_true",
                        help="verify audio/video artifacts only; skip all content review")
    args = parser.parse_args()

    issue = _US_ROOT / "daily-output" / args.issue_date
    if not issue.is_dir():
        print(f"[error] issue directory not found: {issue}")
        return 1

    print(f"[QA] {args.issue_date}")
    report: dict = {
        "date": args.issue_date,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "mechanical": [],
        "semantic": None,
    }

    if args.post_render:
        report["stage"] = "post-render"
        print("  --- post-render artifact checks ---")
        report["mechanical"] = run_post_render(args.issue_date)
        report_path = issue / "review" / "post-render-qa.json"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(
            json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        mech_failed = [c for c in report["mechanical"] if not c["passed"]]
        print(f"\n[QA] report -> {report_path}")
        if mech_failed:
            print(f"[QA] FAILED: {len(mech_failed)} artifact check(s) failed")
            return 2
        print("[QA] PASS (artifacts)")
        return 0

    if not args.semantic_only:
        print("  --- mechanical checks ---")
        report["mechanical"] = run_mechanical(args.issue_date, pre_tts=args.pre_tts)

    if not args.skip_semantic:
        print("  --- semantic review ---")
        if text_llm.is_configured():
            report["semantic"] = run_semantic_review(args.issue_date)
        else:
            print("  [SKIP] text_llm not configured")

    # Determine overall pass/fail.
    mech_failed = [c for c in report["mechanical"] if not c["passed"]]
    semantic = report.get("semantic") or {}
    sem_failed = semantic.get("passed") is False

    report_path = issue / "review" / "qa-report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"\n[QA] report -> {report_path}")

    if mech_failed:
        print(f"[QA] FAILED: {len(mech_failed)} mechanical check(s) failed")
        return 2
    if sem_failed:
        print(f"[QA] FAILED: semantic review found {len(semantic.get('errors', []))} issue(s)")
        return 3
    print("[QA] PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
